FROM postgres:17

RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends postgresql-17-cron; \
    rm -rf /var/lib/apt/lists/*

RUN set -eux; \
    conf_sample="/usr/share/postgresql/17/postgresql.conf.sample"; \
    sed -ri "s/^#?shared_preload_libraries\s*=.*/shared_preload_libraries = 'pg_cron'/" "$conf_sample"; \
    printf "\n# Added for pg_cron\ncron.database_name = 'postgres'\n" >> "$conf_sample"

COPY nuq.sql /docker-entrypoint-initdb.d/010-nuq.sql
